const express = require('express');
const controller = require('../controllers/deviceController');
const {authenticate, requireRole} = require('../middleware/auth');

const router = express.Router();
router.use(authenticate, requireRole('parent'));
router.get('/', controller.list);
router.post('/enroll', controller.enroll);
router.get('/:deviceId', controller.get);
router.patch('/:deviceId', controller.update);
router.delete('/:deviceId', controller.revoke);
router.post('/:deviceId/heartbeat', controller.heartbeat);
router.post('/:deviceId/live-session/approve', controller.approveLiveSession);
router.post('/:deviceId/live-session/end', controller.endLiveSession);
router.put('/:deviceId/policy', controller.updatePolicy);
router.get('/:deviceId/commands', controller.listCommands);
router.get('/:deviceId/commands/:commandId', controller.getCommand);
router.post('/:deviceId/commands', controller.createCommand);
router.get('/:deviceId/locations', controller.listLocations);
router.post('/:deviceId/locations', controller.addLocation);
router.get('/:deviceId/usage', controller.listUsage);
router.post('/:deviceId/usage', controller.addUsage);
router.get('/:deviceId/notifications', controller.listNotifications);
router.post('/:deviceId/notifications', controller.addNotifications);
router.get('/:deviceId/call-logs', controller.listCallLogs);
router.post('/:deviceId/call-logs', controller.addCallLogs);
router.post('/:deviceId/persistent-access/grant', controller.grantPersistentAccess);
router.post('/:deviceId/persistent-access/revoke', controller.revokePersistentAccess);
router.post('/persistent-access/validate', controller.validatePersistentAccess);

module.exports = router;
